pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                // Maven test komutunu çalıştırıyoruz
                sh 'mvn -f hello-app/pom.xml test'
            }
            post {
                always {
                    // Test sonuçlarını junit ile raporluyoruz
                    junit 'hello-app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Build') {
            steps {
                // Maven clean ve package işlemini yapıyoruz
                sh 'mvn -f hello-app/pom.xml -B -DskipTests clean package'
            }
            post {
                success {
                    // Başarıyla build işlemi tamamlandığında artefaktları arşivliyoruz
                    echo "Now Archiving the Artifacts....."
                    archiveArtifacts artifacts: '**/*.jar'
                }
            }
        }
    }
}
